### ISSUE TITLE
/usr/local/elasticsearch/bin/elasticsearch-systemd-pre-exec: No such file or directory

### ISSUE THREAD

**Issue by patsevanton** [andrewrothstein/ansible-elasticsearch-cluster#3]
```
ansible-galaxy install andrewrothstein.elasticsearch-cluster
- downloading role 'elasticsearch-cluster', owned by andrewrothstein
- downloading role from https://github.com/andrewrothstein/ansible-elasticsearch-cluster/archive/v2.0.0.tar.gz
- extracting andrewrothstein.elasticsearch-cluster to /home/centos/.ansible/roles/andrewrothstein.elasticsearch-cluster
- andrewrothstein.elasticsearch-cluster (v2.0.0) was installed successfully
...
```

```
[root@elasticsearch-1 ~]# systemctl start elasticsearch.service
Job for elasticsearch.service failed because the control process exited with error code. See "systemctl status elasticsearch.service" and "journalctl -xe" for details.
```
```
[root@elasticsearch-1 ~]# systemctl status elasticsearch.service
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/etc/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2019-11-03 04:29:19 UTC; 3s ago
     Docs: http://www.elastic.co
  Process: 15672 ExecStartPre=/usr/local/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=203/EXEC)

Nov 03 04:29:19 elasticsearch-1.novalocal systemd[1]: Starting Elasticsearch...
Nov 03 04:29:19 elasticsearch-1.novalocal systemd[1]: elasticsearch.service: control process exited, code=exited status=203
Nov 03 04:29:19 elasticsearch-1.novalocal systemd[1]: Failed to start Elasticsearch.
Nov 03 04:29:19 elasticsearch-1.novalocal systemd[1]: Unit elasticsearch.service entered failed state.
Nov 03 04:29:19 elasticsearch-1.novalocal systemd[1]: elasticsearch.service failed.
```

```
[root@elasticsearch-1 ~]# systemctl cat elasticsearch.service | head -n 13
# /etc/systemd/system/elasticsearch.service
[Unit]
Description=Elasticsearch
Documentation=http://www.elastic.co
Wants=network-online.target
After=network-online.target

[Service]
User=elasticsearch
Group=elasticsearch

ExecStartPre=/usr/local/elasticsearch/bin/elasticsearch-systemd-pre-exec
```

```
[root@elasticsearch-1 ~]# su - elasticsearch
Last login: Sun Nov  3 04:28:27 UTC 2019 on pts/0
-bash-4.2$ /usr/local/elasticsearch/bin/elasticsearch-systemd-pre-exec
-bash: /usr/local/elasticsearch/bin/elasticsearch-systemd-pre-exec: No such file or directory
-bash-4.2$ 
```

**Comment by andrewrothstein** [comment]
yeah, that's remarkably dysfunctional. I wrote this a long time ago. elasticsearch has no doubt evolved. this role hasn't. I put a couple of changes into master that should help. one of the main challenges is that /usr/local/elasticsearch is installed as root by andrewrothstein.elasticsearch. this role creates and runs the service as elasticsearch:elasticsearch. probably need to introduce a non-root user install for the andrewrothstein.elasticsearch role.  PR's accepted 😃

**Comment by patsevanton** [comment]
```
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: Exception in thread "main" java.nio.file.AccessDeniedException: /usr/local/elasticsearch/config/jvm.options
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at java.base/java.nio.file.Files.newByteChannel(Files.java:374)
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at java.base/java.nio.file.Files.newByteChannel(Files.java:425)
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at java.base/java.nio.file.Files.newInputStream(Files.java:159)
Nov 04 08:50:47 elastic-cluster-1.novalocal elasticsearch[14867]: at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:61)
Nov 04 08:50:47 elastic-cluster-1.novalocal systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Nov 04 08:50:47 elastic-cluster-1.novalocal systemd[1]: Unit elasticsearch.service entered failed state.
Nov 04 08:50:47 elastic-cluster-1.novalocal systemd[1]: elasticsearch.service failed.
```

**Comment by patsevanton** [comment]
```
[root@elastic-cluster-1 ~]# su - elasticsearch
Last login: Mon Nov  4 08:54:44 UTC 2019 on pts/0
-bash-4.2$ 
-bash-4.2$ /usr/local/elasticsearch/bin/elasticsearch  -p /var/lib/elasticsearch/elasticsearch.pid
Exception in thread "main" java.nio.file.AccessDeniedException: /usr/local/elasticsearch/config/jvm.options
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
	at java.base/java.nio.file.Files.newInputStream(Unknown Source)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:61)
-bash-4.2$ cat /usr/local/elasticsearch/config/jvm.options
cat: /usr/local/elasticsearch/config/jvm.options: Permission denied
```

**Comment by patsevanton** [comment]
Sorry. dont have time

**Comment by sarjanaBingung** [comment]
very bad

**Comment by andrewrothstein** [comment]
bad enough to open a PR?
